// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           string
	EmailAddress string
	PasswordHash []byte
	PasswordSalt []byte
	CreatedAt    int64
}

type AccountDeletionSession struct {
	ID                   string
	AuthSessionID        string
	SecretHash           []byte
	UserIdentityVerified bool
	CreatedAt            int64
}

type AuthSession struct {
	ID         string
	UserID     string
	SecretHash []byte
	CreatedAt  int64
}

type EmailAddressUpdateSession struct {
	ID                              string
	AuthSessionID                   string
	SecretHash                      []byte
	UserIdentityVerified            bool
	NewEmailAddress                 pgtype.Text
	NewEmailAddressVerificationCode pgtype.Text
	CreatedAt                       int64
}

type PasswordResetSession struct {
	ID                   string
	UserID               string
	SecretHash           []byte
	EmailCodeHash        []byte
	EmailCodeSalt        []byte
	UserIdentityVerified bool
	CreatedAt            int64
}

type PasswordUpdateSession struct {
	ID                   string
	AuthSessionID        string
	SecretHash           []byte
	UserIdentityVerified bool
	CreatedAt            int64
}

type SignupSession struct {
	ID                           string
	SecretHash                   []byte
	EmailAddress                 string
	EmailAddressVerificationCode string
	EmailAddressVerified         bool
	CreatedAt                    int64
}
