// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id, email_address, created_at
FROM account
WHERE id = $1
`

type GetAccountRow struct {
	ID           string
	EmailAddress string
	CreatedAt    int64
}

func (q *Queries) GetAccount(ctx context.Context, id string) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(&i.ID, &i.EmailAddress, &i.CreatedAt)
	return i, err
}
